### ISSUE TITLE
Is this still the correct SDK to use for accessing the Permissions Service?

### ISSUE THREAD

**Issue by ghhtimsgh1970** [paypal/permissions-sdk-dotnet#4]
I notice that on the home page of this repo, it says this SDK is deprecated and to use the newer Paypal. NET SDK.  But that SDK doesn't have any support for the Permissions Service, does it?  If not, should I use this one instead?

**Comment by prashshah** [comment]
Hi @ghhtimsgh1970, can you please provide more insight in your use case for Permissions Service? It will help us in determining the best answer to your question. Thanks.

**Comment by prashshah** [comment]
Hi @ghhtimsgh1970, can you please update with your use case for Permissions Service? If the question is no longer applicable, please let us know too. Thanks.

**Comment by ghhtimsgh1970** [comment]
We are using the Permission Service feature - [the one mentioned here](https://developer.paypal.com/docs/classic/permissions-service/integration-guide/PermissionsAbout/).

We wanted to use an SDK so that we didn't have to interface with NVP or SOAP directly.  This github repo appears to be the correct SDK, but you'll notice that the readme says "Deprecrated, use the REST SDK instead".  But that's not possible because the REST SDK has no support for the Permission Service in it.

Since writing the above question, we just went ahead with this SDK and everything is working fine.  There's really no answer needed except for an update in general to clarify that the REST SDK can't really be used to cover the Permissions Service.

**Comment by pp-randy** [comment]
@ghhtimsgh1970 This is the SDK to use with the Permission Service.  I am going to close this issue out, but let me know if you have any other permission service questions and I will be glad to help.
